-- Security Fix: Make whatsapp-media bucket private
-- This prevents direct public access to media files
-- Access will be controlled via signed URLs generated by edge functions
UPDATE storage.buckets 
SET public = false 
WHERE id = 'whatsapp-media';

-- Security Fix: Remove public INSERT policy on campaign_leads
-- Lead submission should only go through the rate-limited submit-lead edge function
DROP POLICY IF EXISTS "Permitir inserção pública de leads" ON public.campaign_leads;